sudo: required
dist: trusty

language: cpp

# Compiler selection
compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            # GCC 6
            - gcc-6
            - g++-6
            # CLANG 3.8
            - clang-3.8
            - libc++-dev
            # PhysFS
            - libphysfs-dev
            # SDL 2
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libsdl2-ttf-dev

before_install:
- if [ "$CC" = "clang" ]; then 
      export CC="clang-3.8" CXX="clang++-3.8" CXXFLAGS="-ftemplate-depth=1024";
  else
      export CC="gcc-6" CXX="g++-6";
  fi

script:  
- export CC=gcc-6
- export CXX=g++-6
- mkdir build
- cd build && ../external/cmake-3.9.1-Linux-x86_64/bin/cmake .. && make -j4 CC=gcc-6 CXX=g++-6

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bf24f1666021dc4df89a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   false   # default: false
