# AppVeyor configuration for AppVeyor project "Egoboo".
clone_depth: 1

# Build worker image (VM template)
image: Visual Studio 2017

platform:
    - x86
    - x64
configuration:
    - Debug
    - Release

install:
    # depth 32 should be enough.
    git submodule update --init --recursive --depth 32
    
before_build:
    - nuget restore
    - ps: .\install-vsix-appveyor.ps1

build:
    parallel: true                  # enable MSBuild parallel builds
    project: egoboo.sln             # path to Visual Studio solution or project

test_script:
    - ps: |
        $platform = $env:platform
        if ($platform -eq "Win32") { $platform = "x86" }
        vstest.console /Logger:Appveyor /ListDiscoverers /UseVsixExtensions:true
        vstest.console /Logger:Appveyor /ListExecutors /UseVsixExtensions:true
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation /UseVsixExtensions:true "product\idlib-tests\$env:configuration\$env:platform\idlib-tests.exe"
        vstest.console /Logger:Appveyor /Platform:$platform /inIsolation /UseVsixExtensions:true "product\egolib-tests\$env:configuration\$env:platform\egolib-tests.exe"
# if one matrix entry fails, all entries fails
# https://www.appveyor.com/docs/build-configuration#failing-strategy
matrix:
    fast_finish: true
        
notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/7743b26cbf1767e7b3a3
      on_build_success: true
      on_build_failure: true
